#!/usr/bin/env bash
# be-quiet -- Check if logging is suppressed by $LIBRARIAN_LOGLVL
# 
# > be-quiet [+-ADJUSTMENT]
# Use positive ADJUSTMENT if the caller is thought to be handling a subtask.
#
# Author: Jaeho Shin <netj@cs.stanford.edu>
# Created: 2012-11-01
(( LIBRARIAN_LOGLVL += 1 - $SHLVL - ${1:-0} ))
[[ $LIBRARIAN_LOGLVL -lt 0 ]]
