#!/usr/bin/env python
# librarian-project -- add new projects and list all known ones
# 
# Usage example:
# > librarian project add memex --owner mjc --comment "working with blah"
# > librarian project list
#

from metadata_rds import insert_project,enumerate_project
import argparse,sys

parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group()
group.add_argument('--add', '-a', metavar='NAME')
group.add_argument('--list', '-l', action='store_true')
parser.add_argument('--owner', required=True)
parser.add_argument('--comment')
args = parser.parse_args()

print >>sys.stderr, args

# TODO
if args.list:
    print enumerate_project()

else:
    print insert_project()

