#!/usr/bin/env python
# librarian-project -- add new projects and list all known ones
# 
# Usage example:
# > librarian project add memex --owner mjc --comment "working with blah"
# > librarian project list
#

from database_sheetsdb import insert, query
import argparse, sys, datetime

parser = argparse.ArgumentParser()
group = parser.add_mutually_exclusive_group()
group.add_argument('--add', '-a', metavar='NAME')
group.add_argument('--list', '-l', action='store_true')
parser.add_argument('--owner')
parser.add_argument('--comments')
args = parser.parse_args()

if args.list:
    columns, rows = query('Engagements')
    # TODO pretty print these
    print columns
    print rows

else:
    insert('Engagements',
            project=args.add,
            owner=args.owner,
            comments=args.comments,
            date_started=datetime.date.today())


